schema_version: 1

context:
  version: "7.2.0"

package:
  name: pylast
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pylast/pylast-${{ version }}.tar.gz
  sha256: 6b99cdbb556a5bdd2f5711bb42551ef14be2e685f1c24d015f4592b485705ba9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatch-vcs
    - hatchling >=1.27
    - pip
  run:
    - python >=${{ python_min }}
    - httpx2

tests:
  - python:
      imports:
        - pylast
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A Python interface to Last.fm and Libre.fm
  license: Apache-2.0
  license_file:
    - COPYING
    - LICENSE.txt
  homepage: https://github.com/pylast/pylast
  repository: https://github.com/pylast/pylast

extra:
  recipe-maintainers:
    - HeavyTony2
